title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js 
  - bower_components
keep_files:
  - css
  - assets/css
  - assets/js


# Basic Info
church_name: Hartwell Baptist Church 
church_logo_image_path: /assets/img/logo.jpg
church_logo2_image_path: /assets/img/logo.jpg

## Contact Details
phone: (217) 499-0822
church_email: pastor@biblebaptistmattoon.org
facebook: https://www.facebook.com/biblebaptistmattoon/
twitter: https://twitter.com/bbcmattoon
youtube: 
address: 3401 Marion Ave
address2: 
City: Mattoon
State: IL
Zip: '61938'
Google_maps_embed: 



#Collections stuff:

collections:
  - photo_gallery
  - leaders
  - services 






