church_name: Hartwell Baptist Church
church_logo_image_path: /assets/img/logo.jpg
church_logo2_image_path: /assets/img/logo.jpg
main_image: /uploads/background3.jpg
phone: (513) 761-1434
church_email: pastortaylorhbc@yahoo.com
facebook: 'https://www.facebook.com/hartwellbaptistchurch'
twitter: 'https://twitter.com/DrKeithTaylorSr'
youtube:
address: 8222 Monon Avenue
address2:
City: Cincinnati
State: OH
Zip: '45216'
main_blog_image: /uploads/1.jpg
main_sermon_image: /uploads/2.jpg
default_calendar_image: /uploads/hartwell.jpg
lattitude: '39.210653'
longitude: '-84.472477'
map_zoom_level: 14
Google_calendar_id: leonhart4@gmail.com