church_name: Hartwell Baptist Church
church_logo_image_path: /assets/img/logo.jpg
church_logo2_image_path: /assets/img/logo.jpg
phone: (513) 761-1434
church_email: info@hartwellbaptist.org
facebook: 'https://www.facebook.com/kjvbaptisttaylor'
twitter: 'https://twitter.com/DrKeithTaylorSr'
youtube:
address: 8220 Monon Avenue
address2:
City: Cincinnati
State: OH
Zip: '45216'
Google_maps_embed: