# Basic Info
church_name: Hartwell Baptist Church 
church_logo_image_path: /assets/img/logo.jpg
church_logo2_image_path: /assets/img/logo.jpg

## Contact Details
phone: (217) 499-0822
church_email: pastor@biblebaptistmattoon.org
facebook: https://www.facebook.com/biblebaptistmattoon/
twitter: https://twitter.com/bbcmattoon
youtube: 
address: 3401 Marion Ave
address2: 
City: Mattoon
State: IL
Zip: '61938'
Google_maps_embed: 