church_name: Hartwell Baptist Church
church_logo_image_path: /assets/img/logo.jpg
church_logo2_image_path: /assets/img/logo.jpg
main_image: /uploads/background3.jpg
phone: (513) 761-1434
church_email: pastortaylorhbc@yahoo.com
facebook: 'https://www.facebook.com/hartwellbaptistchurch'
twitter: 'https://twitter.com/DrKeithTaylorSr'
youtube:
address: 8222 Monon Avenue
address2:
City: Cincinnati
State: OH
Zip: '45216'
Google_maps_embed:
main_blog_image: /uploads/1.jpg
main_sermon_image: /uploads/2.jpg
default_calendar_image: 